export const actions = {
    profile: {
        DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCHED: "PROFILE_DATA_FETCHED",
        DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
        IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
        DATA_UPDATED: "PROFILE_DATA_UPDATED",
        DATA_POSTED: "PROFILE_DATA_POSTED",
    },
    post: {
        DATA_FETCHING: "POST_DATA_FETCHING",
        DATA_FETCHED: "POST_DATA_FETCHED",
        DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
        DATA_UPDATED: "POST_DATA_UPDATED",
        DATA_DELETED: "POST_DATA_DELETED",
    },
};
