export const actions = {
    profile: {
        DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCHED: "PROFILE_DATA_FETCHED",
        DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
        IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
        DATA_UPDATED: "PROFILE_DATA_UPDATED",
    },
};
